"""
Pydantic schemas and dataclasses for evidence-grounded LLM synthesis.
"""
from __future__ import annotations
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class SynthesisClaim(BaseModel):
    """A factual claim with references to verified EvidenceItem identifiers."""
    text: str = Field(..., description="The factual statement made in the answer")
    evidence_ids: List[str] = Field(default_factory=list, description="List of valid EvidenceItem IDs supporting this claim (e.g. ['E1', 'E2'])")


class SynthesisPayload(BaseModel):
    """Strict schema for structured JSON generated by LLMSynthesizer."""
    answer: str = Field(..., description="The grounded, natural-language response directly answering the user query")
    claims: List[SynthesisClaim] = Field(default_factory=list, description="Deconstructed factual claims mapped to evidence IDs")
    uncertainties: List[str] = Field(default_factory=list, description="Explicit statements regarding uncertainty or uncalibrated confidence")
    justification: str = Field(default="", description="Brief factual summary of supporting evidence (NO hidden chain-of-thought)")


class PostValidationResult(BaseModel):
    """Result of deterministic anti-hallucination validation."""
    is_valid: bool = Field(..., description="Whether the synthesized answer adheres to supplied evidence")
    violations: List[str] = Field(default_factory=list, description="List of detected hallucination or consistency violations")
    sanitized_answer: Optional[str] = Field(default=None, description="Corrected answer if minor adjustment was applied")


class SynthesisResult(BaseModel):
    """Final output of the synthesis layer for the Master Agent."""
    answer: str = Field(..., description="Final natural-language response")
    claims: List[SynthesisClaim] = Field(default_factory=list, description="Structured claims with verified evidence links")
    uncertainties: List[str] = Field(default_factory=list, description="Reported uncertainty disclosures")
    justification: str = Field(default="", description="Summary of evidence justification")
    synthesis_source: Literal["llm", "deterministic_fallback"] = Field(default="llm", description="'llm' or 'deterministic_fallback'")
    fallback_used: bool = Field(default=False, description="Whether deterministic fallback was used")
    fallback_reason: Optional[str] = Field(default=None, description="Reason for fallback if triggered")
    latency_ms: float = Field(default=0.0, description="Synthesis generation latency in milliseconds")
    raw_llm_response: Optional[Dict[str, Any]] = Field(default=None, description="Raw provider output if available")
